apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-v12
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      service: postgres
  replicas: 1
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12
          command: ["docker-entrypoint.sh", "-c","max_connections=200"]
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
              subPath: pgdata
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: postgres-pvc-v12
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    service: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    service: postgres
